name: roc-mini
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scanpy=1.9.6
  - anndata
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - umap-learn
  - python-igraph
  - leidenalg
  - pip
  - pip:
      - gseapy
      - bbknn
      - harmonypy
      - magic-impute
      - mnnpy
